### ISSUE TITLE
arith-error in post-command-hook

### ISSUE THREAD

**Issue by zeltak** [clemera/ivy-explorer#4] opened 2019-01-04 13:00 UTC
i have this in my config

```
(use-package ivy-explorer  
 :ensure t
 :config
(require 'ivy-explorer)
;; use ivy explorer for all file dialogs
(ivy-explorer-mode 1)
;; it's recommended to also use counsel mode
(counsel-mode 1) 
)
```

yet using C-x C-f dosent seem to be launching ivy-explorer but rather regular ivy

any clue?

**Comment by clemera** [comment] 2019-01-04 13:17
Thanks for the report!

What does `C-h c C-x C-f` show you?

**Comment by zeltak** [comment] 2019-01-04 14:07
hi!

yeah same thing. `C-h c C-x C-f` opens an ivy (not ivy-explorer) buffer

best

Z

**Comment by clemera** [comment] 2019-01-04 14:17
That sounds strange. It should open nothing, it should show a message
what command `C-x C-f` actually runs.

**Comment by clemera** [comment] 2019-01-05 12:19
Could you please check `C-h c C-x C-f` again or try `C-h k C-x C-f` and report which command runs?

**Comment by zeltak** [comment] 2019-01-05 13:37
sure ofc 

this is the output of `C-h k C-x C-f`

it opens a buffer with 

```
counsel-find-file is an interactive, autoloaded function defined in
counsel.el.

Signature
(counsel-find-file &optional INITIAL-INPUT)

Documentation
Forward to find-file.

When INITIAL-INPUT is non-nil, use it in the minibuffer during completion.

Key Bindings
counsel-mode-map <open>
ctl-x-map C-f
global-map C-x C-f
term-raw-map C-c C-f
```

happy to help and continue debugging this

Z

**Comment by clemera** [comment] 2019-01-05 16:22
Thanks. So for some reason it fails to bind `C-x C-f` correctly. Probably because you bind `find-file` somwhere else in you init?

If you bind it with:

    (define-key counsel-mode-map (kbd "C-x C-f") 'counsel-explorer) 

it should work?

**Comment by clemera** [comment] 2019-01-07 21:43
@zeltak ping

**Comment by zeltak** [comment] 2019-01-09 06:34
sorry working week :D yes that does work! thx alot

Z

**Comment by carcot** [comment] 2019-07-20 19:16
I am having the same problem, and I think it looks great, too, but it's not working for me. And this solution doesn't work for me unfortunately. :-( Is ivy-explorer know to work in text terminals?

I have been trying to diagnose the problem for a couple hours over multiple days, and the only anomaly I have been able to find so far (other than it doesn't work) is that `ivy-explorer-width` gets set to 10 for some reason. When I change it back to 119 (its original value), though, it still doesn't work.

**Comment by clemera** [comment] 2019-07-21 07:30
>  Is ivy-explorer know to work in text terminals?

Yes if you don't use posframe for display it should work

Could you post your whole config for ivy + ivy-explorer? What is C-x C-f bound to (what does C-h k C-x C-f display)?

**Comment by carcot** [comment] 2019-07-21 16:15
Thanks for your help. Here is my full ivy + ivy-explorer config:

    (use-package ivy
      :diminish (ivy-mode . "")
      :commands (ivy-mode ivy-resume swiper
                          counsel-M-x counsel-ag counsel-expression-history counsel-find-file
                          counsel-git counsel-git-grep counsel-locate counsel-rhythmbox)
      :bind (:map
             ivy-mode-map
             ("C-'" . ivy-avy))
      :config
      (setq ivy-use-virtual-buffers t
            ivy-count-format "%d/%d ")
      (ivy-prescient-mode 1)
      (prescient-persist-mode 1)
      (require 'ivy-explorer)
      (ivy-explorer-mode 1)
      (counsel-mode 1)
      (global-set-key (kbd "M-x") 'amx)
      (define-key counsel-mode-map (kbd "C-x C-f") 'counsel-explorer)

      (setq ivy-use-virtual-buffers t)
      (setq ivy-height 10)
      (setq ivy-count-format "")
      (setq ivy-initial-inputs-alist nil)
      (setq ivy-re-builders-alist
            '((t . ivy--regex-ignore-order)))

      (setq ivy-format-function 'ivy-format-function-line)
      (global-set-key (kbd "C-x l") 'counsel-locate)
      (global-set-key (kbd "C-c C-s") 'swiper)
      (global-set-key (kbd "C-c C-r") 'ivy-resume)
      (global-set-key (kbd "<f6>") 'ivy-resume)
      (global-set-key (kbd "C-c g") 'counsel-git)
      (global-set-key (kbd "C-c j") 'counsel-git-grep)
      (global-set-key (kbd "C-c k") 'counsel-ag)
      (global-set-key (kbd "C-S-o") 'counsel-rhythmbox)
      (define-key read-expression-map (kbd "C-r") 'counsel-expression-history))

and C-h k C-x C-f displays:

    C-x C-f runs the command counsel-explorer (found in counsel-mode-map),
    which is an interactive compiled Lisp function in ‘ivy-explorer.el’.

    It is bound to C-x C-f, <open>, <menu-bar> <file> <new-file>.

    (counsel-explorer &optional INITIAL-INPUT)

    ‘counsel-find-file’ version for ivy explorer.

    INITIAL-INPUT is passed to ‘counsel-find-file’.

A couple of the lines in my config were part of trying to debug the problem. (For example, `(define-key counsel-mode-map (kbd "C-x C-f") 'counsel-explorer)`.)

**Comment by clemera** [comment] 2019-07-21 16:48
Ok, it runs the right command, what exactly happens when you execute it? What versions of ivy/ivy-explorer are you using? I will try to reproduce it when I know your versions.

**Comment by carcot** [comment] 2019-07-21 17:01
This is with ivy version: 20190709.740 and ivy-explorer version: 20190318.1608.

As far as I am aware the output looks exactly the same as it would without ivy-explorer. Just one single-column list along the left side. (All the filenames are short.)

**Comment by clemera** [comment] 2019-07-22 07:56
Thanks, I can reproduce it know. The problem was related to #7. Should be fixed now, you have to wait a bit before MELPA picks it up or use the git version.

**Comment by carcot** [comment] 2019-07-22 18:35
I just tried it out, and unfortunately I'm now receiving the error

    Error in post-command-hook (ivy--queue-exhibit): (arith-error)

which I don't really understand. After that disappears, I get the prompt

    Find file: ~/.emacs.d/|

(| represents the cursor), but that doesn't seem to be working correctly either.

**Comment by clemera** [comment] 2019-07-22 21:38
That's bad! Do you have ivy-posframe-mode enabled, too? Could you try to set:

    (setq debug-on-message "Error in post-command-hook")

and post the backtrace here?

**Comment by carcot** [comment] 2019-07-23 03:15
I don't know what `ivy-posframe-mode` is, but I don't think so. Not intentionally, and I can't find it with `C-h f`, `C-h v`, or `C-h a`.

After setting `debug-on-message`, this is what I get when I press `C-x C-f`:

[debug.txt](https://github.com/clemera/ivy-explorer/files/3419968/debug.txt)

Is this what you are looking for?

**Comment by clemera** [comment] 2019-07-23 06:25
> Is this what you are looking for?

Yes, thanks. Could you try to run `C-x C-f` in a different directroy? I believe it has something to do with long file names.

**Comment by carcot** [comment] 2019-07-23 12:58
Yes, I just ran the command in a directory with only files named "a", "b", and "c" and got the same error.

**Comment by clemera** [comment] 2019-07-23 14:30
Not sure what's going on, I have to make some tests and investigate...

**Comment by carcot** [comment] 2019-07-26 15:33
Thanks for your help. I don't understand the nature of the error, but if there's some way for me to help, please let me know. I do know Emacs Lisp and some parts of Emacs fairly well.

**Comment by clemera** [comment] 2019-09-09 19:30
@carcot Sorry for the delay I will look into this the next few days. Do you still have the problem? With my current ivy version (0.12.0) I can't reproduce it.

**Comment by carcot** [comment] 2019-09-09 22:55
Yes, with the latest counsel, ivy, and ivy-explorer installed, I still get the same error.

**Comment by clemera** [comment] 2019-09-10 08:49
Okay thanks, I will retry with a fresh Emacs session without my config then.

**Comment by clemera** [comment] 2019-09-10 19:16
I tried but still can't reproduce the error. I have used the config you posted before with a fresh install of the required packages. Please repost your config (if it has changed) + the Emacs version your are using and exact steps to reproduce.

**Comment by carcot** [comment] 2019-09-10 21:23
Hmm. I am running Emacs 26.3 and I just used the exact config I had posted before (and the latest versions of counsel, ivy, and ivy-explorer), and I got the same error: immediately after Emacs startup I type `C-x C-f`.

**Comment by clemera** [comment] 2019-09-10 22:37
I'm running 26.3 as well. Could you try creating a file with the following content:


    (package-initialize)

    (use-package ivy
      :diminish (ivy-mode . "")
      :commands (ivy-mode ivy-resume swiper
                          counsel-M-x counsel-ag counsel-expression-history counsel-find-file
                          counsel-git counsel-git-grep counsel-locate counsel-rhythmbox)
      :bind (:map
             ivy-mode-map
             ("C-'" . ivy-avy))
      :config
      (setq ivy-use-virtual-buffers t
            ivy-count-format "%d/%d ")
      (ivy-prescient-mode 1)
      (prescient-persist-mode 1)
      (require 'ivy-explorer)
      (ivy-explorer-mode 1)
      (counsel-mode 1)
      (global-set-key (kbd "M-x") 'amx)
      (define-key counsel-mode-map (kbd "C-x C-f") 'counsel-explorer)

      (setq ivy-use-virtual-buffers t)
      (setq ivy-height 10)
      (setq ivy-count-format "")
      (setq ivy-initial-inputs-alist nil)
      (setq ivy-re-builders-alist
            '((t . ivy--regex-ignore-order)))

      (setq ivy-format-function 'ivy-format-function-line)
      (global-set-key (kbd "C-x l") 'counsel-locate)
      (global-set-key (kbd "C-c C-s") 'swiper)
      (global-set-key (kbd "C-c C-r") 'ivy-resume)
      (global-set-key (kbd "<f6>") 'ivy-resume)
      (global-set-key (kbd "C-c g") 'counsel-git)
      (global-set-key (kbd "C-c j") 'counsel-git-grep)
      (global-set-key (kbd "C-c k") 'counsel-ag)
      (global-set-key (kbd "C-S-o") 'counsel-rhythmbox)
      (define-key read-expression-map (kbd "C-r") 'counsel-expression-history))

And then start emacs using `emacs -Q -l <file>`. Then do M-x `counsel-mode` and try `C-x C-f`. Do you still get the error? What are the dir contents where you get the error?

**Comment by carcot** [comment] 2019-09-10 23:01
That seems to work, I think. Are you supposed to be able to navigate the multi-column file list with the arrow keys or C-f, C-n, etc.? (I'm not able to do that.)

**Comment by clemera** [comment] 2019-09-11 06:37
Not the arrow keys currently but C-f/b/p/n/a/e should navigate the grid. If you don't get the error anymore than this error probably comes from another config related to ivy in your config.

**Comment by jhenahan** [comment] 2019-09-27 12:39
I also got this, and disabling `ivy-rich-mode` seems to have stopped the error. After some more fiddling, it looks like the resolution was to set

```
(setcdr (assq t ivy-format-functions-alist) #'ivy-format-function-line)
```
rather than

```
(setq ivy-format-function 'ivy-format-function-line)
```

and now they both seem to be working together properly.

**Comment by clemera** [comment] 2019-09-30 12:19
@jhenahan Thanks! I will retry this with ivy-rich, and probably let bind the format functions, I guess.

**Comment by jhenahan** [comment] 2019-09-30 12:23
I actually spoke too soon. I still get the arith-error on really large directories even with this change, so it seems I was only masking the problem. I'll see if I can figure out something easily reproducible.

**Comment by clemera** [comment] 2020-06-27 09:44
See #12

**Closed as completed by clemera** 2020-06-27 09:44 UTC
